server:
  port: 8763

spring:
  application:
    name: eurka-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


logging:
  level:
    root: info
  path: ./logs
  config: classpath:logback-spring.xml
